title: Rockhopper 1776
description: Military history, wargaming, boardgame tools, and hobbyist software projects.
url: "https://www.rockhopper1776.com"
lang: en-US
author: Kevin Conway
markdown: kramdown
